title: Caleb M. Keller
description: Data strategist - from the shop floor, to the C-suite
url: https://wrathagom.github.io
author: Caleb M. Keller

permalink: /blog/:title

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
